# Netlify Configuration for Reem Resort Frontend

[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "dist"
  
  # Use Node.js 20+
  NODE_VERSION = "20"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard)
# VITE_API_URL=https://hotel-management-reem-resort-1.onrender.com

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache manifest files
[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Don't cache index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
